# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AndroidWorld
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Emerging computer control agents, which execute human tasks by controlling
  computer interfaces with minimal human supervision, can enhance human productivity
  and application accessibility. Yet, progress in this field will be driven by realistic 
  and reproducible benchmarks. We present AndroidWorld, a fully-functioning Android environment 
  that provides reward signals for 116 programmatic task workflows across 20 real-world 
  Android apps. Unlike existing interactive environments which provide a static test set, AndroidWorld 
  supports task workflows that can be parameterized and expressed in natural language in unlimited 
  ways, thus enabling testing on a much larger and realistic suite of tasks. Reward signals are 
  derived from the computer's system state, making them durable across task variations and also 
  extensible across different applications. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
